/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mvbos.mychatapp;

import java.awt.event.KeyEvent;

/**
 *
 * @author mbecker
 */
public class ChatWindow extends javax.swing.JFrame {

    //server
    private Server serv;
    private boolean serverMode;
    //client
    private Client client;
    private boolean clientMode = false;
    //Default
    private StringBuilder buffer = new StringBuilder();

    private void startClient() {
        client = new Client(tfConName.getText());
        client.connect(tfConUrl.getText(), Integer.parseInt(tfConPort.getText()));
        listenServer();

        clientMode = true;
    }

    private void stopClient() {
        clientMode = false;
        client.sendMessageToServer(Server.Comands.END_CHAT.getComand());
        client.close();
        buffer.delete(0, buffer.length());
        btnConnect.setSelected(false);
    }

    private void startServer() {
        serv = new Server(Integer.parseInt(tfConPort.getText()), "server_" + tfConName.getText());
        serv.runService();

        //mode service with client
        startClient();

        serverMode = true;
    }

    private void stopServer() {
        //mode service with client
        stopClient();

        serv.stopService();

        serverMode = false;
        btnStartServer.setSelected(false);
    }

    //to listen service and enable other functions
    private void listenServer() {

        new Thread() {

            @Override
            public void run() {

                while (clientMode) {
                    String fromServer = client.listenServer();
                    if (fromServer != null) {
                        if (fromServer.trim().equals(Server.Comands.END_CHAT.getComand())) {
                            buffer.append("\n").append("Server say good bye!");
                            updateRecive();

                            break;
                        }
                        //else
                        buffer.append(fromServer);
                        updateRecive();

                    }
                }

                stopClient();

            }
        }.start();
    }
    
    private void updateRecive(){
        //tfRecive.setText(buffer.toString());
        tfRecive.append(buffer.toString());
        buffer.delete(0, buffer.length());
    }

    private void sendConversation() {
        String msg = tfSend.getText();
        client.sendMessageToServer(msg);//send to server
        tfSend.setText("");

        //buffer.append("You say: ").append(msg).append("\n");
        //updateRecive();
    }

    public ChatWindow() {
        initComponents();
        tfConName.setText(System.getProperty("user.name"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        btnStartServer = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfSend = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfRecive = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        tfConUrl = new javax.swing.JTextField();
        tfConPort = new javax.swing.JTextField();
        tfConName = new javax.swing.JTextField();
        btnConnect = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStartServer.setText("Start server");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnConnect, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), btnStartServer, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartServerActionPerformed(evt);
            }
        });

        tfSend.setColumns(20);
        tfSend.setRows(5);
        tfSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSendKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tfSend);

        tfRecive.setColumns(20);
        tfRecive.setEditable(false);
        tfRecive.setRows(5);
        jScrollPane2.setViewportView(tfRecive);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        tfConUrl.setText("localhost");

        tfConPort.setText("4321");

        tfConName.setText("becker");

        btnConnect.setText("Connect on server");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnStartServer, org.jdesktop.beansbinding.ELProperty.create("${!selected}"), btnConnect, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        jLabel1.setText("IP / Port / Name");

        jLabel2.setText("OR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 338, Short.MAX_VALUE)
                        .addComponent(btnSend))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfConUrl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfConPort, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfConName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfConUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfConPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfConName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConnect)
                    .addComponent(btnStartServer)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnSend)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartServerActionPerformed
        if (!serverMode) {
            startServer();
        } else {
            stopServer();
        }
    }//GEN-LAST:event_btnStartServerActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        sendConversation();
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed

        if (!clientMode) {
            startClient();
        } else {
            stopClient();
        }

    }//GEN-LAST:event_btnConnectActionPerformed

private void tfSendKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSendKeyReleased
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        sendConversation();
    }
}//GEN-LAST:event_tfSendKeyReleased
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConnect;
    private javax.swing.JButton btnSend;
    private javax.swing.JToggleButton btnStartServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfConName;
    private javax.swing.JTextField tfConPort;
    private javax.swing.JTextField tfConUrl;
    private javax.swing.JTextArea tfRecive;
    private javax.swing.JTextArea tfSend;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
